fs = require('fs')
path = require('path')
mkdirp = require('mkdirp')
Datastore = require('nedb')
gui = require('nw.gui')
Shell = gui.Shell
Window = gui.Window
cuid = require('cuid')
hljs = require('highlight.js')
Q         = require('./js/q.js')
FileUtils = require('./js/lib/fileutils.js')
# require './js/lib/textarea_extension.js'
